id: docker-compose-config 6
info:
  name: docker-compose.yml exposure
  author: meme-lord,blckraven,geeknik
  severity: medium
  tags: config,exposure,devops
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /docker-compose-dev.yml HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - 'regex("^version: ", body) && contains(body, "services:")'
      - type: status
        status:
          - 200
