id: application-yaml 3

info:
  name: application.yaml detection
  author: Cristi vlad (@cristivlad25)
  severity: info
  description: Finds Application YAML files which often contain sensitive information.

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /application.yaml HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        condition: or
        words:
          - "runtime:"
          - "spring:"
          - "datasource:"
          - "platform:"
          - "server:"
          - "job:"

      - type: status
        status:
          - 200

      - type: dsl
        condition: or
        dsl:
          - "!contains(tolower(body), '<html')"
          - "!contains(tolower(body), '<body')"
          - "!contains(tolower(body), '</h1>')"
          - "!contains(tolower(body), '</h2>')"
          - "!contains(tolower(body), '</h3>')"
          - "!contains(tolower(body), '<?xml')"