id: manageengine-applications-manager
info:
  name: ZOHO ManageEngine Applications Manager
  author: dhiyaneshDK
  severity: info
  reference: https://fofa.so/result?qbase64=YXBwPSJaT0hPLU1hbmFnZUVuZ2luZS1BcHBsaWNhdGlvbnMtTWFuYWdlciI%3D
  tags: panel,zoho,manageengine
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /index.do HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Applications Manager Login Screen</title>'
      - type: status
        status:
          - 200
