id: prometheus-targets-endpoint
info:
  name: Prometheus targets API endpoint
  author: geeknik
  severity: info
  description: The targets endpoint exposes services belonging to the infrastructure, including their roles and labels. In addition to showing the target machine addresses, the endpoint also exposes metadata labels that are added by the target provider. These labels are intended to contain non-sensitive values, like the name of the server or its description, but various cloud platforms may automatically expose sensitive data in these labels, oftentimes without the developerâ€™s knowledge.
  reference: https://jfrog.com/blog/dont-let-prometheus-steal-your-fire/
  tags: prometheus,exposure
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /api/v1/targets HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - '{"status":"success","data":'
          - 'Labels'
        condition: and
      - type: word
        part: header
        words:
          - 'application/json'
