id: http-headers-strict-transport-security

info:
  name: Missing HTTP Header - Strict-Transport-Security
  author: nvsecurity
  severity: low
  reference:
    - https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#strict-transport-security-hsts
    - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
  description: |
    The website is missing the `Strict-Transport-Security` security header. The lack of this header *could* allow an attacker to intercept the user's session.
  metadata:
    max-request: 1
  tags: misconfig,headers

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    host-redirects: true
    max-redirects: 3
    matchers-condition: or
    matchers:
      - type: dsl
        name: strict-transport-security
        dsl:
          - "!regex('(?i)strict-transport-security', header)"
          - "status_code != 301 && status_code != 302 && status_code != 404"
        condition: and
