id: zoho-manageengine-applications-manager
info:
  name: ZOHO-ManageEngine-Applications-Manager
  author: dhiyaneshDK
  severity: info
  reference: https://fofa.so/result?qbase64=YXBwPSJaT0hPLU1hbmFnZUVuZ2luZS1BcHBsaWNhdGlvbnMtTWFuYWdlciI%3D
  tags: panel,zoho
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /index.do HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko)
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Applications Manager Login Screen</title>'
      - type: status
        status:
          - 200
