id: rails-database-config
info:
  name: Ruby-on-Rails Database Configuration Exposure
  author: pdteam,geeknik
  severity: low
  tags: config,exposure,rails
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /config/database.yml HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "adapter:"
          - "database:"
          - "production:"
        condition: and
        part: body
      - type: status
        status:
          - 200
