id: amazon-docker-config-disclosure
info:
  name: Dockerrun AWS Configuration Exposure
  author: pdteam
  severity: medium
  tags: config,exposure,aws,devops
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /Dockerrun.aws.json HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers:
      - type: word
        words:
          - 'AWSEBDockerrunVersion'
          - 'containerDefinitions'
        condition: and
