id: cloud-storage-misconfig
info:
  name: Security Misconfigurations in Cloud Storage
  severity: medium
  description: Detects potential misconfigurations in cloud storage settings on the target
author: qaisar
tags:
  - cloud
  - security
requests:
- method: GET
  path:
    - "/storage"
    - "/list-buckets"
  matchers:
  - type: regex
    part: body
    regex:
    - "<Bucket>.*<\/Bucket>"
