id: coep-misconfig
info:
  name: COEP Misconfiguration
  severity: medium
  description: Detects potential Cross-Origin Embedder Policy (COEP) misconfigurations in the target
author: qaisar afridi
tags:
  - web
  - coep
requests:
- method: GET
  path:
    - "/"
    - "/home"
  matchers:
  - type: regex
    part: headers
    regex:
    - "Cross-Origin-Embedder-Policy:.*"
