id: configuration-listing

name: Sensitive Configuration Files Listing
severity: medium

requests:
  - method: GET
    paths:
      - "HOSTNAME/config/"

    patterns:
      - "Index of /config"
      - "Parent Directory"

