id: configuration-listing
info:
  name: Sensitive Configuration Files Listing
  author: j33n1k4
  severity: medium
  description: directory listing of sensitive files
  reference: https://www.exploit-db.com/ghdb/7014
  tags: config,listing,exposures
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /config/ HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Index of /configs"
          - "Parent Directory"
        condition: and
      - type: status
        status:
          - 200
