id: coop-misconfig
info:
  name: COOP Misconfiguration
  severity: medium
  description: Detects potential Cross-Origin Opener Policy (COOP) misconfigurations in the target
author: qaisar afridi
tags:
  - web
  - coop
requests:
- method: GET
  path:
    - "/"
    - "/home"
  matchers:
  - type: regex
    part: headers
    regex:
    - "Cross-Origin-Opener-Policy:.*"
