id: detect-drone-config
info:
  name: Detect Drone Configuration
  author: geeknik
  description: Drone is a Container-Native, Continuous Delivery Platform -- https://github.com/drone/drone
  severity: high
  tags: config,exposure,drone
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /.drone.yml HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "kind:"
          - "name:"
          - "steps:"
        condition: and
      - type: status
        status:
          - 200
