
id: misconfig-workflow

info:
  name: Misconfiguration Security Checks
  author: thevillagehacker
  description: A simple workflow that runs all misconfig related nuclei templates against the target.

workflows:
  - template: misconfiguration/
  - tags: misconfig