id: php-fpm-config
info:
  name: PHP-FPM Config file disclosure
  author: sheikhrishad
  severity: low
  tags: config,exposure,php
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /php-fpm.conf HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "FPM Configuration"
          - "Pool Definitions"
        condition: and
      - type: status
        status:
          - 200
