id: springboot-autoconfig 1
info:
  name: Detect Springboot autoconfig Actuator
  author: pussycat0x
  severity: low
  description: Displays an auto-configuration report showing all auto-configuration candidates and the reason why they 'were' or 'were not' applied.
  tags: springboot,exposure
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /autoconfig HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "positiveMatches"
          - "AuditAutoConfiguration#auditListener"
          - "EndpointAutoConfiguration#beansEndpoint"
        condition: and
      - type: status
        status:
          - 200
