id: svnserve-config
info:
  name: svnserve config file disclosure
  author: sheikhrishad
  severity: low
  tags: config,exposure,svnserve
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /svnserve.conf HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "This file controls the configuration of the svnserve daemon"
      - type: status
        status:
          - 200
