id: symfony-security-config2

info:
  name: Symfony Security Configuration Exposure
  author: dahse89
  severity: info
  reference:
    - https://symfony2-document.readthedocs.io/en/latest/book/security.html
    - https://symfony.com/doc/current/reference/configuration/security.html
  tags: config,exposure,symfony


requests:
  - raw:
      - |
        GET /app/config/security.yml HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "security:"
          - "firewalls:"
          - "access_control:"
        condition: and
        part: body