id: symfony-database-config
info:
  name: Symfony Database Configuration Exposure
  author: pdteam,geeknik
  severity: high
  tags: config,exposure
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /config/databases.yml HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "text/html"
        negative: true
      - type: status
        status:
          - 200
      - type: word
        words:
          - "class:"
          - "param:"
        condition: and
        part: body
