id: tugboat-config-exposure
info:
  name: Tugboat configuration file exposure
  description: Tugboat is a command line tool for interacting with your DigitalOcean droplets.
  reference: https://github.com/petems/tugboat
  author: geeknik
  severity: critical
  tags: tugboat,config,exposure
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /.tugboat HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "authentication"
          - "access_token"
          - "ssh_user"
        condition: and
    extractors:
      - type: regex
        part: body
        regex:
          - 'access_token: .*'
