id: wamp-server-configuration
info:
  name: default-wamp-server-page
  author: pussycat0x
  severity: medium
  description: Wamp default page will expose sensitive configuration and vhosts.
  reference: https://www.exploit-db.com/ghdb/6891.
  tags: wamp,exposure
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET / HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - 'contains(tolower(body), "wampserver")'
      - type: status
        status:
          - 200
