id: zend-config-file
info:
  name: Zend Configuration File
  author: pdteam
  severity: high
  tags: config,exposure,zend,php
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /application/configs/application.ini HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "resources.db.params.password"
      - type: word
        words:
          - "text/plain"
        part: header
      - type: status
        status:
          - 200
