id: git-config
info:
  name: Git Config Disclosure
  author: pdteam,pikpikcu,Mah3Sec_
  severity: medium
  description: Searches for the pattern /.git/config and log file on passed URLs.
  tags: config,git,exposure
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /.git/config HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
        Accept-Language: en-US,en;q=0.5
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 0
        Connection: close
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "[core]"
      - type: dsl
        dsl:
          - "!contains(tolower(body), '<html')"
          - "!contains(tolower(body), '<body')"
        condition: and
      - type: status
        status:
          - 200
