id: ansible-config-disclosure
name: Ansible Configuration Exposure
severity: medium

requests:
  - method: GET
    paths:
      - "HOSTNAME/ansible.cfg"
    patterns:
      - '\[defaults\]'
      - '\[inventory\]'
