id: firebase-config-exposure 2
info:
  name: Firebase Config Exposure
  author: geeknik
  reference: https://github.com/firebase/firebaseui-web/blob/master/demo/public/sample-config.js
  severity: high
  tags: firebase,exposure,config
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /config.js HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "apiKey:"
          - "authDomain:"
          - "databaseURL:"
          - "storageBucket:"
        condition: and
      - type: status
        status:
          - 200
