id: kubernetes-kustomization-disclosure
info:
  name: Kubernetes Kustomization Disclosure
  author: dhiyaneshDk
  severity: medium
  reference: https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/kubernetes-kustomization-disclosure.json
  tags: exposure,config
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /kustomization.yml HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        part: body
        condition: or
        words:
          - "apiVersion:"
          - "resources:"
          - "namespace:"
          - "commonLabels:"
          - "Kustomization"
      - type: word
        part: body
        condition: or
        words:
          - "yaml"
          - "yml"
      - type: status
        status:
          - 200
