id: prometheus-exposed-panel
info:
  name: Prometheus.io exposed panel
  author: organiccrap
  severity: low
  tags: panel,prometheus
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /graph HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Prometheus Time Series Collection and Processing Server</title>'
