id: prometheus-exporter-detect
info:
  name: Prometheus exporter detect
  author: jarijaas
  severity: info
  description: Prometheus exporter detector
  tags: panel
  reference: https://github.com/prometheus/prometheus/wiki/Default-port-allocations
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET / HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko)
    matchers-condition: and
    matchers:
      - type: word
        words:
          - Exporter # Exporters have "Exporter" in the page title (e.g, Node Exporter, Bind Exporter and so on)
          - /metrics
        condition: and
