id: aws-s3-misconfig
info:
  name: AWS S3 Bucket Misconfiguration
  severity: high
  description: Detects potential AWS S3 bucket misconfigurations in the target
author: qaisar afridi
tags:
  - cloud
  - aws
  - s3
requests:
- method: GET
  path:
    - "/s3"
    - "/list-buckets"
  matchers:
  - type: regex
    part: body
    regex:
    - "<Name>.*<\/Name>"
