id: awstats-config

name: AWStats config
severity: info

requests:
  - method: GET
    paths:
      - "HOSTNAME/awstats/"
      - "HOSTNAME/awstats.conf"

    patterns:
      - "AWSTATS CONFIGURE|Index of /awstats"
      - "MAIN SETUP SECTION|Parent Directory"
