id: swagger-api53

info:
  name: Public Swagger API
  author: pdteam
  severity: info
  tags: exposure,api,swagger


requests:
  - raw:
      - |
        GET /api/v1/swagger-ui/swagger.json HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "swagger:"
          - "Swagger 2.0"
          - "\"swagger\":"
          - "Swagger UI"
          - "**token**:"
        condition: or
      - type: status
        status:
          - 200
