id: keycloak-openid-config 1

info:
  name: Keycloak openid-config
  author: rodnt
  severity: info
  reference: https://issues.jboss.org/browse/KEYCLOAK-571
  tags: keycloak,config

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /.well-known/openid-configuration HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - 'issuer'
          - 'authorization_endpoint'
          - 'token_endpoint'
          - 'userinfo_endpoint'
          - 'jwks_uri'
        condition: and