id: magento-config 1
info:
  name: Magento Config Disclosure
  author: geeknik
  severity: medium
  tags: config,exposure,magento
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /app/etc/local.xml HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "text/xml"
        part: header
      - type: word
        words:
          - "Magento"
        part: body
