id: netlify-cms
info:
  name: Netlify CMS Admin Panel
  author: sullo
  severity: info
  tags: panel
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /admin/index.html HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko)
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Netlify CMS"
        part: body
