id: front-page-misconfig 1

info:
  name: FrontPage configuration information discloure
  author: JTeles,pikpikcu
  severity: info
  reference: https://docs.microsoft.com/en-us/archive/blogs/fabdulwahab/security-protecting-sharepoint-server-applications

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /_vti_inf.html HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "vti_extenderversion:"
          - "FPVersion="
        part: body

      - type: status
        status:
          - 200
