id: docker-registry
info:
  name: Docker Registry Listing
  author: puzzlepeaches
  severity: medium
  tags: docker,devops
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /v2/_catalog HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"repositories":'
      - type: word
        words:
          - "application/json"
        part: header
