id: kubernetes-version
info:
  name: Kubernetes Version Exposure
  author: raesene
  description: Searches for exposed Kubernetes API servers which return version information unauthenticated
  severity: info
  tags: tech,k8s,kubernetes,devops
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /version HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers:
      - type: word
        words:
          - "gitVersion"
          - "goVersion"
          - "platform"
        condition: and
