id: kubernetes-resource-report
info:
  name: Detect Overview Kubernetes Resource Report
  author: pussycat0x
  severity: medium
  description: Information Disclosure of Kubernetes Resource Report
  tags: kubernetes,exposure
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET / HTTP/1.1
        Host: {{Subdomains}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Overview - Kubernetes Resource Report"
      - type: status
        status:
          - 200
