id: kubernetes-metrics

info:
  name: Detect Kubernetes Exposed Metrics
  author: pussycat0x
  severity: low
  description: Information Disclosure of Garbage Collection
  tags: kubernetes,exposure,devops
  reference: https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#metrics-in-kubernetes

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /metrics HTTP/1.1
        Host: {{Subdomains}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        condition: and
        words:
          - "namespace"
          - "HELP"
          - "TYPE"
          - "kube"

      - type: status
        status:
          - 200