id: kubernetes-pods-api 1
info:
  name: Kubernetes Pods API
  author: ilovebinbash,geeknik,0xtavian
  severity: critical
  description: When the service port is available, anyone can execute commands inside the container. See https://github.com/officialhocc/Kubernetes-Kubelet-RCE for inspiration.
  reference: https://blog.binaryedge.io/2018/12/06/kubernetes-being-hijacked-worldwide/
  tags: k8,unauth,kubernetes,devops
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /pods HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "apiVersion"
        part: body
      - type: word
        words:
          - "application/json"
        part: header
      - type: status
        status:
          - 200
