id: misconfigured-docker
info:
  name: Misconfigured Docker on Default Port
  author: dhiyaneshDK
  severity: critical
  reference: https://madhuakula.com/content/attacking-and-auditing-docker-containers-using-opensource/attacking-docker-containers/misconfiguration.html
  tags: docker,unauth,devops
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /images/json HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"ParentId":'
          - '"Container":'
          - '"Labels":'
        condition: and
      - type: status
        status:
          - 200
