id: wordpress-accessible-wpconfig 2
info:
  name: WordPress accessible wp-config
  author: Kiblyn11,zomsop82,madrobot,geeknik,daffainfo
  severity: high
  tags: wordpress,backups

requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /.wp-config.php.swp HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers-condition: and
    matchers:
      - type: word
        words:
          - DB_NAME
          - WPENGINE_ACCOUNT
        part: body
      - type: status
        status:
          - 200
