id: nginx-config
info:
  name: Nginx Config file disclosure
  author: sheikhrishad
  severity: info
  tags: config,exposure,nginx
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100
    raw:
      - |
        GET /nginx.conf HTTP/1.1
        Host: {{Subdomains}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "server"
          - "listen"
          - "server_name"
        condition: and
      - type: status
        status:
          - 200
